#! /bin/sh

#Auto Start
sxhkd &
~/.config/polybar/launch.sh &
xrandr --output DP-0 --mode 1680x1050 --pos 3840x0 --rotate left --output DP-1 --off --output DP-2 --off --output DP-3 --off --output HDMI-0 --mode 1920x1080 --pos 0x300 --rotate normal --output eDP-1-1 --primary --mode 1920x1080 --pos 1920x300 --rotate normal
feh --bg-scale /usr/share/wallpapers/Mine/Astranout.jpg  /usr/share/wallpapers/Mine/v_deep_puırple.png /usr/share/wallpapers/Mine/sci_fi_city.png
compton -b &
flameshot &
#syncthing&
dropbox start &
##Keyboard Stuff
setxkbmap -option caps:escape us
xmodmap -e "keysym Menu = Super_R"
xset r rate 300 25
#exec_always xrandr --output DP-0 --off --output DP-1 --off --output DP-2 --off --output DP-3 --off --output HDMI-0 --mode 1920x1080 --pos 0x0 --rotate normal --output eDP-1-1 --mode 1920x1080 --pos 1920x0 --rotate normal
#exec_always  xrandr --output DP-0 --primary --mode 1680x1050 --pos 3840x0 --rotate left --output DP-1 --off --output DP-2 --off --output DP-3 --off --output HDMI-0 --mode 1920x1080 --pos 0x300 --rotate normal --output eDP-1-1 --mode 1920x1080 --pos 1920x300 --rotate normal

#bspc monitor -d I II III IV V VI VII VIII IX X 

bspc monitor HDMI-0 -d I II III IV V VI VII IX X
bspc monitor eDP-1-1 -d I II III IV V VI VII IX X
bspc monitor DP-0 -d I II III IV V VI VII IX X 

bspc config split_ratio                  0.50

bspc config borderless_monocle           true
bspc config gapless_monocle              true
bspc config focus_follows_pointer        true
bspc config single_monocle               true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config border_width                  2
bspc config window_gap                    5
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0

#Colors
bspc config normal_border_color		      "#0f0f0f"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#d0e1f9"
bspc config presel_feedback_color	      "#d0e1f9"
bspc config urgent_border_color 	      "#fe4a49"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
